Travis build script

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,6 +1,65 @@
-#!/usr/bin/env bash
-set -e # halt script on error
+#!/bin/bash
+set -e # Exit with nonzero exit code if anything fails
 
-JEKYLL_ENV=production bundle exec jekyll build
-#bundle exec htmlproofer ./_site
+SOURCE_BRANCH="source"
+TARGET_BRANCH="master"
+TARGET_FOLDER="_site"
+function doCompile {
+	JEKYLL_ENV=production bundle exec jekyll build
+}
+
+# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
+if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
+	echo "Skipping deploy; just doing a build."
+	JEKYLL_ENV=production bundle exec jekyll build
+	exit 0
+fi
+
+# Save some useful information
+REPO=`git config remote.origin.url`
+SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
+SHA=`git rev-parse --verify HEAD`
+
+# Clone the existing gh-pages for this repo into out/
+# Create a new empty branch if gh-pages doesn't exist yet (should only happen on first deply)
+git clone $REPO $TARGET_FOLDER
+cd $TARGET_FOLDER
+git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
+cd ..
+
+# Clean out existing contents
+rm -rf $TARGET_FOLDER/**/* || exit 0
+
+# Run our compile script
+doCompile
+
+# Now let's go have some fun with the cloned repo
+cd $TARGET_FOLDER
+git config user.name "Travis CI"
+git config user.email "$COMMIT_AUTHOR_EMAIL"
+
+# If there are no changes to the compiled out (e.g. this is a README update) then just bail.
+if [ $(git status --porcelain | wc -l) -lt 1 ] ; then
+    echo "No changes to the output on this push; exiting."
+    exit 0
+fi
+
+# Commit the "changes", i.e. the new version.
+# The delta will show diffs between new and old versions.
+git add -A .
+git commit -m "Deploy to GitHub Pages: ${SHA}"
+
+# Get the deploy key by using Travis's stored variables to decrypt deploy_key.enc
+ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
+ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
+ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
+ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
+openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in ../script/deploy_key.enc -out ../script/deploy_key -d
+chmod 600 ../script/deploy_key
+eval `ssh-agent -s`
+ssh-add ../script/deploy_key
+
+# Now that we're all set up, we can push.
+git push $SSH_REPO $TARGET_BRANCH
+
 
